# fly.toml app configuration file generated for bomb-still-dust-3356 on 2025-04-11T12:25:23-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bomb-still-dust-3356'
primary_region = 'ord'

[build]
  [build.args]
    GO_VERSION = '1.23.1'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
