# fly.toml app configuration file generated for bomb-cold-water-1753 on 2025-09-05T13:19:56-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bomb-cold-water-1753'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
